name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload repository to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: 22
          source: .
          target: /var/www/ukgovcomms
          overwrite: true

      - name: Create .env on server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: 22
          script: |
            set -euo pipefail
            cd /var/www/ukgovcomms
            {
              echo "DB_HOST=${{ secrets.DB_HOST }}"
              echo "DB_NAME=${{ secrets.DB_NAME }}"
              echo "DB_USER=${{ secrets.DB_USER }}"
              echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
              echo "MPLBACKEND=Agg"
            } > .env

      - name: Install dependencies on server (in-repo venv)
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: 22
          script: |
            set -euo pipefail
            cd /var/www/ukgovcomms
            python3 -m venv .venv
            ./.venv/bin/pip install --upgrade pip setuptools wheel
            ./.venv/bin/pip install -r requirements.txt

      - name: Restart ukgovcomms service
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: 22
          script: |
            set -euo pipefail
            sudo systemctl daemon-reload
            sudo systemctl restart ukgovcomms
            sudo systemctl status ukgovcomms --no-pager -l || true
