name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Upload the repo to the server (excludes untracked/ignored files by default)
      - name: Upload repository to server
        uses: appleboy/scp-action@v0.1.8
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: 22
          source: .
          target: /var/www/ukgovcomms
          overwrite: true

      # Create/update .env on the server from GitHub Secrets
      - name: Create .env on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: 22
          script: |
            set -euo pipefail
            cd /var/www/ukgovcomms
            # Write .env (add/remove keys to match your app)
            echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            # Optional: any other runtime settings
            echo "MPLBACKEND=Agg" >> .env

      # Ensure in-repo venv exists; install exact deps from requirements.txt
      - name: Install dependencies on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: 22
          script: |
            set -euo pipefail
            cd /var/www/ukgovcomms
            python3 -m venv .venv
            ./.venv/bin/pip install --upgrade pip setuptools wheel
            ./.venv/bin/pip install -r requirements.txt

      # Restart your service to pick up new code & venv
      - name: Restart Gunicorn service
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart ukgovcomms
            sudo systemctl status ukgovcomms --no-pager -l || true
