name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file from secrets
        run: |
          echo "BLUESKY_HANDLE=${{ secrets.BLUESKY_HANDLE }}" > .env
          echo "BLUESKY_APP_PASSWORD=${{ secrets.BLUESKY_APP_PASSWORD }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_USER=ukgovcomms_admin" >> .env
          echo "DB_NAME=UKGovComms" >> .env

      - name: Upload files via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: 22
          source: "."
          target: "/var/www/ukgovcomms"
          rm: true

      - name: Install dependencies on server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: 22
          script: |
            source /var/www/.venvs/ukgovcomms/bin/activate
            cd /var/www/ukgovcomms
            pip install --upgrade pip
            pip install -r requirements.txt

